spring:
  application:
    name: expenses-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    stream:
      bindings:
        categoryExpensesAdded-in-0:
          destination: categoryExpensesAdded-events
#        categoryExpensesRemoved-in-0:
#          destination: categoryExpensesRemoved-events
