server:
  port: 8081
eureka:
  server:
    port: 8760
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
feign:
  circuitbreaker:
    enabled: true
spring:
  cloud:
    stream:
      bindings:
        - categoryExpensesAdded-in-0:
            destination: category-events
        - categoryExpensesRemoved-in-0:
            destination: category-events
