server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alvie97/billtracker.git
          search-paths:
            - config-data
          default-label: "refactor-microservices"