server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/billtracker
          search-paths:
            - config-data
          default-label: "refactor-microservices"